name: ServerAutoBackuper
main: Teaclon\ServerAutoBackuper\Main
author: Teaclon
version: "1.0.5"
api: 
 - 1.0.0
 - 1.12.0
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
 - 3.0.0-ALPHA12
 - 3.0.0
 - 3.0.1
 - 3.0.4
 - 3.0.6
 - 3.0.7
 - 3.0.8
 - 3.1.0
 - 3.3.0
 - 3.3.1
 - 3.3.2
 - 4.0.0
load: STARTUP

softdepend: ["TSeriesAPI"]